# coding: utf-8

"""
    MasterMind Service Manager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: gaea@zhaw.ch
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.volume_api import VolumeApi  # noqa: E501
from swagger_client.rest import ApiException


class TestVolumeApi(unittest.TestCase):
    """VolumeApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.volume_api.VolumeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_volume(self):
        """Test case for create_volume

        Create a volume with the given name  # noqa: E501
        """
        pass

    def test_delete_volume(self):
        """Test case for delete_volume

        Remove volume with given name  # noqa: E501
        """
        pass

    def test_get_volumes(self):
        """Test case for get_volumes

        Obtain a list of defined volumes  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
