# coding: utf-8

"""
    MasterMind Service Manager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: gaea@zhaw.ch
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.stack_api import StackApi  # noqa: E501
from swagger_client.rest import ApiException


class TestStackApi(unittest.TestCase):
    """StackApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.stack_api.StackApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_stack(self):
        """Test case for delete_stack

        Delete services of a stack  # noqa: E501
        """
        pass

    def test_deploy_stack(self):
        """Test case for deploy_stack

        Deploy a new stack  # noqa: E501
        """
        pass

    def test_get_stack(self):
        """Test case for get_stack

        Get the list of services of a stack  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
