# coding: utf-8

"""
    MasterMind Service Manager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: gaea@zhaw.ch
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.swarm_api import SwarmApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSwarmApi(unittest.TestCase):
    """SwarmApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.swarm_api.SwarmApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_swarm_status(self):
        """Test case for swarm_status

        Get swarm status  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
