# coding: utf-8

"""
    MasterMind Service Manager

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: gaea@zhaw.ch
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.swarm import Swarm  # noqa: E501
from swagger_client.rest import ApiException


class TestSwarm(unittest.TestCase):
    """Swarm unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSwarm(self):
        """Test Swarm"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.swarm.Swarm()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
