---
swagger: "2.0"
info:
  description: ""
  version: "0.1.0"
  title: "MasterMind Service Manager"
  contact:
    email: "gaea@zhaw.ch"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "127.0.0.1"
basePath: "/v1"
schemes:
- "http"
paths:
  /engine/status:
    get:
      tags:
      - "Engine"
      summary: "Docker Engine healthcheck"
      description: ""
      operationId: "controllers.default_controller.get_engine_status"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "engine"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/Engine"
      responses:
        200:
          description: "OK"
      x-tags:
      - tag: "Engine"
  /stack:
    post:
      tags:
      - "Stack"
      summary: "Deploy a new stack"
      description: ""
      operationId: "controllers.default_controller.deploy_stack"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "stack"
        description: "Create a Stack"
        required: true
        schema:
          $ref: "#/definitions/Stack"
      responses:
        200:
          description: "OK"
      x-tags:
      - tag: "Stack"
    put:
      tags:
      - "Stack"
      summary: "Update an existing stack"
      description: ""
      operationId: "controllers.default_controller.update_stack"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "stack"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/Stack"
      responses:
        200:
          description: "OK"
      x-tags:
      - tag: "Stack"
  /stack/{name}:
    get:
      tags:
      - "Stack"
      summary: "Get the list of services of a stack"
      description: "Get a list of all services of a stack"
      operationId: "controllers.default_controller.get_stack_status"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "path"
        description: ""
        required: true
        type: "string"
      - in: "body"
        name: "stack_parameters"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/Engine"
      responses:
        200:
          description: "Successfully retrieved services"
      x-tags:
      - tag: "Stack"
    delete:
      tags:
      - "Stack"
      summary: "Delete services and networks of a stack"
      description: "Delete services and networks of a stack"
      operationId: "controllers.default_controller.delete_stack"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "path"
        description: ""
        required: true
        type: "string"
      - in: "body"
        name: "stack_parameters"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/Engine"
      responses:
        200:
          description: "Successfully deleted services"
      x-tags:
      - tag: "Stack"
definitions:
  Engine:
    type: "object"
    required:
    - "engine-url"
    properties:
      engine-url:
        type: "string"
  Stack:
    type: "object"
    required:
    - "engine-url"
    - "name"
    properties:
      name:
        type: "string"
      compose-file:
        type: "string"
      engine-url:
        type: "string"
      compose-vars:
        type: "string"
