---
swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "MasterMind Service Manager"
  contact:
    email: "gaea@zhaw.ch"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "127.0.0.1:8080"
basePath: "/v1"
schemes:
- "http"
paths:
  /stack:
    post:
      tags:
      - "Stack"
      summary: "Deploy a new stack"
      description: ""
      operationId: "deploy_stack"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "stack"
        description: "Create a Stack"
        required: true
        schema:
          $ref: "#/definitions/Stack"
      responses:
        200:
          description: "OK"
      x-tags:
      - tag: "Stack"
      x-swagger-router-controller: "api.controllers.stack_controller"
  /stack/{name}:
    get:
      tags:
      - "Stack"
      summary: "Get the list of services of a stack"
      description: "Get a list of all services of a stack"
      operationId: "get_stack"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "path"
        description: ""
        required: true
        type: "string"
      - in: "body"
        name: "getStack"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/Stack"
      responses:
        200:
          description: "Successfully retrieved services"
      x-tags:
      - tag: "Stack"
      x-swagger-router-controller: "api.controllers.stack_controller"
    delete:
      tags:
      - "Stack"
      summary: "Delete services of a stack"
      description: "Delete services of a stack"
      operationId: "delete_stack"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "path"
        description: ""
        required: true
        type: "string"
      - in: "body"
        name: "deleteStack"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/Stack"
      responses:
        200:
          description: "Successfully deleted services"
      x-tags:
      - tag: "Stack"
      x-swagger-router-controller: "api.controllers.stack_controller"
definitions:
  Stack:
    type: "object"
    required:
    - "engine-url"
    - "name"
    properties:
      name:
        type: "string"
      compose-file:
        type: "string"
      compose-vars:
        type: "string"
      engine-url:
        type: "string"
      ca-cert:
        type: "string"
      cert:
        type: "string"
      cert-key:
        type: "string"