---
swagger: "2.0"
info:
  description: ""
  version: "0.1.0"
  title: "MasterMind Service Manager"
  contact:
    email: "gaea@zhaw.ch"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "127.0.0.1:8080"
basePath: "/v1"
schemes:
- "http"
paths:
  /stack:
    post:
      tags:
      - "Stack"
      summary: "Deploy a new stack"
      description: ""
      operationId: "deploy_stack"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "stack_data"
        in: "formData"
        description: "Stack Information"
        required: true
        type: "string"
      - name: "ca_cert"
        in: "formData"
        description: "ca-cert"
        required: false
        type: "file"
      - name: "cert"
        in: "formData"
        description: "cert"
        required: false
        type: "file"
      - name: "cert_key"
        in: "formData"
        description: "cert-key"
        required: false
        type: "file"
      responses:
        200:
          description: "OK"
      x-tags:
      - tag: "Stack"
      x-swagger-router-controller: "swagger_server.controllers.stack_controller"
  /stack/{name}:
    post:
      tags:
      - "Stack"
      summary: "Get existing stack"
      description: ""
      operationId: "get_stack"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "path"
        description: ""
        required: true
        type: "string"
      - name: "stack_data"
        in: "formData"
        description: "Docker engine url"
        required: true
        type: "string"
      - name: "ca_cert"
        in: "formData"
        description: "ca-cert"
        required: false
        type: "file"
      - name: "cert"
        in: "formData"
        description: "cert"
        required: false
        type: "file"
      - name: "cert_key"
        in: "formData"
        description: "cert-key"
        required: false
        type: "file"
      responses:
        200:
          description: "OK"
      x-tags:
      - tag: "Stack"
      x-swagger-router-controller: "swagger_server.controllers.stack_controller"
    delete:
      tags:
      - "Stack"
      summary: "Delete an existing stack"
      description: ""
      operationId: "delete_stack"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "path"
        description: ""
        required: true
        type: "string"
      - name: "stack_data"
        in: "formData"
        description: "Docker engine url"
        required: true
        type: "string"
      - name: "ca_cert"
        in: "formData"
        description: "ca-cert"
        required: false
        type: "file"
      - name: "cert"
        in: "formData"
        description: "cert"
        required: false
        type: "file"
      - name: "cert_key"
        in: "formData"
        description: "cert-key"
        required: false
        type: "file"
      responses:
        200:
          description: "OK"
      x-tags:
      - tag: "Stack"
      x-swagger-router-controller: "swagger_server.controllers.stack_controller"
definitions: {}