# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Stack(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, name: str=None, compose_file: str=None, compose_vars: str=None, engine_url: str=None, ca_cert: str=None, cert: str=None, cert_key: str=None):
        """
        Stack - a model defined in Swagger

        :param name: The name of this Stack.
        :type name: str
        :param compose_file: The compose_file of this Stack.
        :type compose_file: str
        :param compose_vars: The compose_vars of this Stack.
        :type compose_vars: str
        :param engine_url: The engine_url of this Stack.
        :type engine_url: str
        :param ca_cert: The ca_cert of this Stack.
        :type ca_cert: str
        :param cert: The cert of this Stack.
        :type cert: str
        :param cert_key: The cert_key of this Stack.
        :type cert_key: str
        """
        self.swagger_types = {
            'name': str,
            'compose_file': str,
            'compose_vars': str,
            'engine_url': str,
            'ca_cert': str,
            'cert': str,
            'cert_key': str
        }

        self.attribute_map = {
            'name': 'name',
            'compose_file': 'compose-file',
            'compose_vars': 'compose-vars',
            'engine_url': 'engine-url',
            'ca_cert': 'ca-cert',
            'cert': 'cert',
            'cert_key': 'cert-key'
        }

        self._name = name
        self._compose_file = compose_file
        self._compose_vars = compose_vars
        self._engine_url = engine_url
        self._ca_cert = ca_cert
        self._cert = cert
        self._cert_key = cert_key

    @classmethod
    def from_dict(cls, dikt) -> 'Stack':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Stack of this Stack.
        :rtype: Stack
        """
        return deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """
        Gets the name of this Stack.

        :return: The name of this Stack.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """
        Sets the name of this Stack.

        :param name: The name of this Stack.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")

        self._name = name

    @property
    def compose_file(self) -> str:
        """
        Gets the compose_file of this Stack.

        :return: The compose_file of this Stack.
        :rtype: str
        """
        return self._compose_file

    @compose_file.setter
    def compose_file(self, compose_file: str):
        """
        Sets the compose_file of this Stack.

        :param compose_file: The compose_file of this Stack.
        :type compose_file: str
        """

        self._compose_file = compose_file

    @property
    def compose_vars(self) -> str:
        """
        Gets the compose_vars of this Stack.

        :return: The compose_vars of this Stack.
        :rtype: str
        """
        return self._compose_vars

    @compose_vars.setter
    def compose_vars(self, compose_vars: str):
        """
        Sets the compose_vars of this Stack.

        :param compose_vars: The compose_vars of this Stack.
        :type compose_vars: str
        """

        self._compose_vars = compose_vars
