# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Swarm(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, engine_url: str=None, ca_cert: str=None, cert: str=None, cert_key: str=None):
        """
        Swarm - a model defined in Swagger

        :param engine_url: The engine_url of this Swarm.
        :type engine_url: str
        :param ca_cert: The ca_cert of this Swarm.
        :type ca_cert: str
        :param cert: The cert of this Swarm.
        :type cert: str
        :param cert_key: The cert_key of this Swarm.
        :type cert_key: str
        """
        self.swagger_types = {
            'engine_url': str,
            'ca_cert': str,
            'cert': str,
            'cert_key': str
        }

        self.attribute_map = {
            'engine_url': 'engine-url',
            'ca_cert': 'ca-cert',
            'cert': 'cert',
            'cert_key': 'cert-key'
        }

        self._engine_url = engine_url
        self._ca_cert = ca_cert
        self._cert = cert
        self._cert_key = cert_key

    @classmethod
    def from_dict(cls, dikt) -> 'Swarm':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Swarm of this Swarm.
        :rtype: Swarm
        """
        return deserialize_model(dikt, cls)
