# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Swarm(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, engine_url: str=None, ca_cert: str=None, cert: str=None, cert_key: str=None):
        """
        Swarm - a model defined in Swagger

        :param engine_url: The engine_url of this Swarm.
        :type engine_url: str
        :param ca_cert: The ca_cert of this Swarm.
        :type ca_cert: str
        :param cert: The cert of this Swarm.
        :type cert: str
        :param cert_key: The cert_key of this Swarm.
        :type cert_key: str
        """
        self.swagger_types = {
            'engine_url': str,
            'ca_cert': str,
            'cert': str,
            'cert_key': str
        }

        self.attribute_map = {
            'engine_url': 'engine-url',
            'ca_cert': 'ca-cert',
            'cert': 'cert',
            'cert_key': 'cert-key'
        }

        self._engine_url = engine_url
        self._ca_cert = ca_cert
        self._cert = cert
        self._cert_key = cert_key

    @classmethod
    def from_dict(cls, dikt) -> 'Swarm':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Swarm of this Swarm.
        :rtype: Swarm
        """
        return deserialize_model(dikt, cls)

    @property
    def engine_url(self) -> str:
        """
        Gets the engine_url of this Swarm.

        :return: The engine_url of this Swarm.
        :rtype: str
        """
        return self._engine_url

    @engine_url.setter
    def engine_url(self, engine_url: str):
        """
        Sets the engine_url of this Swarm.

        :param engine_url: The engine_url of this Swarm.
        :type engine_url: str
        """
        if engine_url is None:
            raise ValueError("Invalid value for `engine_url`, must not be `None`")

        self._engine_url = engine_url

    @property
    def ca_cert(self) -> str:
        """
        Gets the ca_cert of this Swarm.

        :return: The ca_cert of this Swarm.
        :rtype: str
        """
        return self._ca_cert

    @ca_cert.setter
    def ca_cert(self, ca_cert: str):
        """
        Sets the ca_cert of this Swarm.

        :param ca_cert: The ca_cert of this Swarm.
        :type ca_cert: str
        """

        self._ca_cert = ca_cert

    @property
    def cert(self) -> str:
        """
        Gets the cert of this Swarm.

        :return: The cert of this Swarm.
        :rtype: str
        """
        return self._cert

    @cert.setter
    def cert(self, cert: str):
        """
        Sets the cert of this Swarm.

        :param cert: The cert of this Swarm.
        :type cert: str
        """

        self._cert = cert

    @property
    def cert_key(self) -> str:
        """
        Gets the cert_key of this Swarm.

        :return: The cert_key of this Swarm.
        :rtype: str
        """
        return self._cert_key

    @cert_key.setter
    def cert_key(self, cert_key: str):
        """
        Sets the cert_key of this Swarm.

        :param cert_key: The cert_key of this Swarm.
        :type cert_key: str
        """

        self._cert_key = cert_key
